[custom]

;设置规则标志位
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🪐谷歌cn,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=🪐谷歌cn,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🪐谷歌cn,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🪐谷歌cn,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
ruleset=⚓ github,https://raw.githubusercontent.com/Special-Care/ACL4SSR/refs/heads/main/Clash/Ruleset/Docker.list
ruleset=⚓ github,https://raw.githubusercontent.com/Special-Care/ACL4SSR/refs/heads/main/Clash/Ruleset/Github.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=Ⓜ️ 微软,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🪐谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🪐谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=🪐谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/Special-Care/ACL4SSR/refs/heads/main/Clash/Providers/Ruleset/Twitter.yaml
ruleset=📲 电报消息,[]DOMAIN-SUFFIX,x.com
ruleset=📲 电报消息,[]DOMAIN-SUFFIX,azul.com
ruleset=📲 电报消息,[]DOMAIN-SUFFIX,twimg.com
ruleset=📲 电报消息,[]DOMAIN-SUFFIX,twitter.com
ruleset=💬 OpenAi,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🌈挑剩下的,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🎯 全球直连`select`select`[]DIRECT`[]🚀 节点选择1`[]🚀 节点选择2`[]🚀 节点选择3
custom_proxy_group=🚀 节点选择1`select`.*
custom_proxy_group=🚀 节点选择2`select`.*
custom_proxy_group=🚀 节点选择3`select`.*
custom_proxy_group=⚓ github`select`[]🚀 节点选择1`[]🚀 节点选择2`[]🚀 节点选择3
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择1`[]🚀 节点选择2`[]🚀 节点选择3
custom_proxy_group=Ⓜ️ 微软`select`[]DIRECT`[]🚀 节点选择1`[]🚀 节点选择2`[]🚀 节点选择3
custom_proxy_group=🪐谷歌cn`select`[]DIRECT`[]🚀 节点选择1`[]🚀 节点选择2`[]🚀 节点选择3
custom_proxy_group=🪐谷歌`select`[]DIRECT`[]🚀 节点选择1`[]🚀 节点选择2`[]🚀 节点选择3
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择1`[]🚀 节点选择2`[]🚀 节点选择3
custom_proxy_group=📲 电报消息`select`[]🚀 节点选择1`[]🚀 节点选择2`[]🚀 节点选择3
custom_proxy_group=💬 OpenAi`select`[]🚀 节点选择1`[]🚀 节点选择2`[]🚀 节点选择3
custom_proxy_group=🌈挑剩下的`select`[]DIRECT`[]🚀 节点选择1`[]🚀 节点选择2`[]🚀 节点选择3

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
